from pathlib import Path
root = Path('.')
changes = {
    'settings.html': [
        ('<html lang="en">','<html lang="fr">'),
        ('<title>Settings — FleetCommand</title>','<title>Paramètres — FleetCommand</title>'),
        ('<div class="section-title" style="font-size:18px;">Settings</div>','<div class="section-title" style="font-size:18px;">Paramètres</div>'),
        ('<div class="section-subtitle">Preferences & access (mock)</div>','<div class="section-subtitle">Préférences et accès (maquette)</div>'),
        ('<button class="btn btn-ghost btn-sm" onclick="showToast(\'info\',\'Saved\',\'Settings saved (mock)\')">Save</button>','<button class="btn btn-ghost btn-sm" onclick="showToast(\'info\',\'Enregistré\',\'Paramètres enregistrés (maquette)\')">Enregistrer</button>'),
        ('<button class="btn btn-primary btn-sm" onclick="showToast(\'success\',\'Updated\',\'Preferences updated (mock)\')">Apply</button>','<button class="btn btn-primary btn-sm" onclick="showToast(\'success\',\'Mis à jour\',\'Préférences mises à jour (maquette)\')">Appliquer</button>'),
        ('<div class="settings-row-label">Delivery Alerts</div>','<div class="settings-row-label">Alertes de livraison</div>'),
        ('<div class="settings-row-desc">Receive alerts for delays & status changes</div>','<div class="settings-row-desc">Recevoir des alertes en cas de retard ou de changement de statut</div>'),
        ('<div class="settings-row-label">Maintenance Reminders</div>','<div class="settings-row-label">Rappels maintenance</div>'),
        ('<div class="settings-row-desc">Get reminders before service windows</div>','<div class="settings-row-desc">Recevoir des rappels avant les créneaux d’entretien</div>'),
        ('<div class="settings-row-label">Driver Messages</div>','<div class="settings-row-label">Messages conducteurs</div>'),
        ('<div class="settings-row-desc">New message notifications</div>','<div class="settings-row-desc">Notifications de nouveaux messages</div>'),
        ('<div class="settings-section-header">Account</div>','<div class="settings-section-header">Compte</div>'),
        ('<div class="settings-row-label">Organization</div>','<div class="settings-row-label">Organisation</div>'),
        ('<div class="settings-row-desc">FleetCommand Logistics</div>','<div class="settings-row-desc">FleetCommand Logistics</div>'),
        ('<div class="settings-row-label">Admin Role</div>','<div class="settings-row-label">Rôle administrateur</div>'),
        ('<div class="settings-row-desc">Manage fleet, dispatch & approvals</div>','<div class="settings-row-desc">Gérer la flotte, dispatch et approbations</div>'),
        ('<div class="settings-row-label">Security</div>','<div class="settings-row-label">Sécurité</div>'),
        ('<div class="settings-row-desc">Two-factor authentication</div>','<div class="settings-row-desc">Authentification à deux facteurs</div>'),
        ("initApp('Settings <span class=\"topbar-subtitle\">— Preferences</span>');","initApp('Paramètres <span class=\"topbar-subtitle\">— Préférences</span>');"),
    ],
    'messages.html': [
        ('<html lang="en">','<html lang="fr">'),
        ('<div class="chat-sidebar-header">Driver Conversations</div>','<div class="chat-sidebar-header">Conversations conducteurs</div>'),
        ('<div class="section-title" id="chatTitle" style="font-size:16px;">Select a driver</div>','<div class="section-title" id="chatTitle" style="font-size:16px;">Sélectionnez un conducteur</div>'),
        ('<div class="section-subtitle" id="chatSubtitle">Messages will appear here</div>','<div class="section-subtitle" id="chatSubtitle">Les messages apparaissent ici</div>'),
        ('onclick="showToast(\'info\',\'Compose\',\'Mock compose message\')">✍️ Compose</button>','onclick="showToast(\'info\',\'Rédiger\',\'Message fictif créé\')">✍️ Rédiger</button>'),
        ('placeholder="Write a message…"','placeholder="Écrire un message…"'),
        ("showToast('success','Sent','Message sent');","showToast('success','Envoyé','Message envoyé');"),
        ("initApp('Messages <span class=\"topbar-subtitle\">— Dispatch Inbox</span>');","initApp('Messages <span class=\"topbar-subtitle\">— Boîte de réception</span>');"),
    ],
    'dispatch.html': [
        ('<html lang="en">','<html lang="fr">'),
        ('<div class="section-title" style="font-size:18px;">Dispatch Board</div>','<div class="section-title" style="font-size:18px;">Tableau de dispatch</div>'),
        ('<div class="section-subtitle">Drag cards to reprioritize (mock)</div>','<div class="section-subtitle">Glisser les cartes pour re-prioriser (maquette)</div>'),
        ('onclick="showToast(\'info\',\'Refresh\',\'Dispatch updated\')">⟳ Refresh</button>','onclick="showToast(\'info\',\'Actualiser\',\'Tableau de dispatch mis à jour\')">⟳ Actualiser</button>'),
        ('onclick="showToast(\'success\',\'Created\',\'New dispatch task created\')">➕ New Task</button>','onclick="showToast(\'success\',\'Créé\',\'Nouvelle tâche de dispatch créée\')">➕ Nouvelle tâche</button>'),
        ('<span>Pending</span>','<span>En attente</span>'),
        ('<span>In Progress</span>','<span>En cours</span>'),
        ('<span>Delayed</span>','<span>En retard</span>'),
        ('<span>Completed</span>','<span>Terminé</span>'),
        ("card.addEventListener('click', ()=> showToast('info','Delivery', d.id+' selected'));","card.addEventListener('click', ()=> showToast('info','Livraison', d.id+' sélectionnée'));"),
        ("showToast('success','Dispatch','Moved '+id+' to new lane');","showToast('success','Dispatch', id+' déplacée vers une nouvelle colonne');"),
        ("initApp('Dispatch <span class=\"topbar-subtitle\">— Dispatch Board</span>');","initApp('Dispatch <span class=\"topbar-subtitle\">— Tableau de dispatch</span>');"),
    ],
    'drivers.html': [
        ('<html lang="en">','<html lang="fr">'),
        ('<title>Drivers — FleetCommand</title>','<title>Conducteurs — FleetCommand</title>'),
        ('<div class="section-title" style="font-size:18px;">Driver Management</div>','<div class="section-title" style="font-size:18px;">Gestion des conducteurs</div>'),
        ('<div class="section-subtitle">8 drivers registered · 5 currently active</div>','<div class="section-subtitle">8 conducteurs enregistrés · 5 actuellement actifs</div>'),
        ('onclick="showToast(\'info\',\'Export\',\'Driver report exported to CSV\')">📤 Export</button>','onclick="showToast(\'info\',\'Exporter\',\'Rapport conducteurs exporté vers CSV\')">📤 Exporter</button>'),
        ('onclick="showToast(\'info\',\'Sort\',\'Sorted by name\')">Sort: Name</button>','onclick="showToast(\'info\',\'Tri\',\'Trié par nom\')">Trier : Nom</button>'),
        ('<button class="btn btn-primary btn-sm" onclick="openAddDriver()">➕ Add Driver</button>','<button class="btn btn-primary btn-sm" onclick="openAddDriver()">➕ Ajouter conducteur</button>'),
        ('<input type="text" placeholder="Search drivers…" id="driverSearch" oninput="filterDrivers()">','<input type="text" placeholder="Rechercher des conducteurs…" id="driverSearch" oninput="filterDrivers()">'),
        ('<div class="chip active" data-filter="all" onclick="setFilter(this,\'all\')">All</div>','<div class="chip active" data-filter="all" onclick="setFilter(this,\'all\')">Tout</div>'),
        ('<div class="chip" data-filter="online" onclick="setFilter(this,\'online\')">🟢 Online</div>','<div class="chip" data-filter="online" onclick="setFilter(this,\'online\')">🟢 En ligne</div>'),
        ('<div class="chip" data-filter="driving" onclick="setFilter(this,\'driving\')">🚛 Driving</div>','<div class="chip" data-filter="driving" onclick="setFilter(this,\'driving\')">🚛 En route</div>'),
        ('<div class="chip" data-filter="offline" onclick="setFilter(this,\'offline\')">⚫ Offline</div>','<div class="chip" data-filter="offline" onclick="setFilter(this,\'offline\')">⚫ Hors ligne</div>'),
        ('<option>All Cities</option>','<option>Toutes les villes</option>'),
        ('<option>Los Angeles</option>','<option>Casablanca</option>'),
        ('<option>Chicago</option>','<option>Rabat</option>'),
        ('<option>New York</option>','<option>Marrakech</option>'),
        ('<option>Dallas</option>','<option>Tanger</option>'),
        ('<span style="font-size:13px;font-weight:600;color:var(--text-muted);" id="tableCount">8 drivers</span>','<span style="font-size:13px;font-weight:600;color:var(--text-muted);" id="tableCount">8 conducteurs</span>'),
        ('<th>Driver</th><th>Status</th><th>City</th><th>Truck</th>','<th>Conducteur</th><th>Statut</th><th>Ville</th><th>Camion</th>'),
        ('<th>Trips</th><th>Rating</th><th>Risk</th><th>License Exp</th><th>Earnings</th><th>Actions</th>','<th>Trajets</th><th>Note</th><th>Risque</th><th>Permis</th><th>Revenus</th><th>Actions</th>'),
        ('<span style="font-size:11px;color:var(--text-muted);">🚛 ${d.truck || \'Unassigned\'}</span>','<span style="font-size:11px;color:var(--text-muted);">🚛 ${d.truck || \'Non attribué\'}</span>'),
        ('<div class="stat-lbl">This Month</div>','<div class="stat-lbl">Ce mois-ci</div>'),
        ('<div class="stat-lbl">Total Trips</div>','<div class="stat-lbl">Trajets totaux</div>'),
        ('<div class="stat-lbl">On-Time Rate</div>','<div class="stat-lbl">Taux de ponctualité</div>'),
        ('<div class="stat-lbl">Miles Driven</div>','<div class="stat-lbl">Km parcourus</div>'),
        ('onclick="event.stopPropagation();showToast(\'info\',\'Location\',\'Tracking ${d.name}\')">📡','onclick="event.stopPropagation();showToast(\'info\',\'Position\',\'Suivi ${d.name}\')">📡'),
        ('<button class="btn btn-ghost btn-xs" onclick="openDriverProfile(\'${d.id}\')">View</button>','<button class="btn btn-ghost btn-xs" onclick="openDriverProfile(\'${d.id}\')">Voir</button>'),
        ('<button class="btn btn-ghost btn-xs" onclick="openChat(\'${d.id}\')">Chat</button>','<button class="btn btn-ghost btn-xs" onclick="openChat(\'${d.id}\')">Discussion</button>'),
        ('<div class="modal-title">Driver Profile</div>','<div class="modal-title">Profil conducteur</div>'),
        ('<div class="form-label">Phone</div>','<div class="form-label">Téléphone</div>'),
        ('<div class="form-label">City</div>','<div class="form-label">Ville</div>'),
        ('<div class="form-label">License Expiry</div>','<div class="form-label">Permis valide jusqu\'à</div>'),
        ('<div class="form-label">Assigned Truck</div>','<div class="form-label">Camion attribué</div>'),
        ('<div style="font-size:10px;color:var(--text-muted);">Rating</div>','<div style="font-size:10px;color:var(--text-muted);">Note</div>'),
        ('{l:\'Total Trips\',v:d.trips.toLocaleString(),c:\'var(--text-primary)\'},','{l:\'Trajets totaux\',v:d.trips.toLocaleString(),c:\'var(--text-primary)\'},'),
        ('{l:\'Deliveries\',v:d.deliveries.toLocaleString(),c:\'var(--accent-green)\'},','{l:\'Livraisons\',v:d.deliveries.toLocaleString(),c:\'var(--accent-green)\'},'),
        ('{l:\'On-Time Rate\',v:d.ontime,c:\'var(--accent-cyan)\'},','{l:\'Taux de ponctualité\',v:d.ontime,c:\'var(--accent-cyan)\'},'),
        ('{l:\'Miles Driven\',v:(d.miles/1000).toFixed(0)+\'k\',c:\'var(--accent-violet)\'},','{l:\'Km parcourus\',v:(d.miles/1000).toFixed(0)+\'k\',c:\'var(--accent-violet)\'},'),
        ('<button class="btn btn-ghost btn-sm" onclick="closeModal()">Close</button>','<button class="btn btn-ghost btn-sm" onclick="closeModal()">Fermer</button>'),
        ('<button class="btn btn-primary btn-sm" onclick="showToast(\'success\',\'Updated\',\'Driver profile saved\');closeModal()">Save Changes</button>','<button class="btn btn-primary btn-sm" onclick="showToast(\'success\',\'Mis à jour\',\'Profil conducteur enregistré\');closeModal()">Enregistrer</button>'),
        ('<div class="modal-title">Add New Driver</div>','<div class="modal-title">Ajouter un conducteur</div>'),
        ('<label class="form-label">First Name</label><input class="form-control" placeholder="John">','<label class="form-label">Prénom</label><input class="form-control" placeholder="Prénom">'),
        ('<label class="form-label">Last Name</label><input class="form-control" placeholder="Smith">','<label class="form-label">Nom</label><input class="form-control" placeholder="Nom">'),
        ('<label class="form-label">Phone Number</label><input class="form-control" placeholder="+1 (555) 000-0000">','<label class="form-label">Téléphone</label><input class="form-control" placeholder="+212 6 00 00 00 00">'),
        ('<label class="form-label">City</label><input class="form-control" placeholder="Los Angeles">','<label class="form-label">Ville</label><input class="form-control" placeholder="Casablanca">'),
        ('<label class="form-label">License Number</label><input class="form-control" placeholder="CDL-A 123456">','<label class="form-label">Numéro de permis</label><input class="form-control" placeholder="123456789">'),
        ('<label class="form-label">License Expiry</label><input class="form-control" type="date">','<label class="form-label">Validité du permis</label><input class="form-control" type="date">'),
        ('<label class="form-label">Assign Truck</label>','<label class="form-label">Attribuer un camion</label>'),
        ('<option value="">— Unassigned —</option>','<option value="">— Non attribué —</option>'),
        ('<button class="btn btn-ghost" onclick="closeModal()">Cancel</button>','<button class="btn btn-ghost" onclick="closeModal()">Annuler</button>'),
        ('<button class="btn btn-primary" onclick="showToast(\'success\',\'Driver Added\',\'New driver has been registered\');closeModal()">Add Driver</button>','<button class="btn btn-primary" onclick="showToast(\'success\',\'Conducteur ajouté\',\'Nouveau conducteur enregistré\');closeModal()">Ajouter le conducteur</button>'),
        ("initApp('Drivers <span class=\"topbar-subtitle\">— Driver Management</span>');","initApp('Conducteurs <span class=\"topbar-subtitle\">— Gestion des conducteurs</span>');"),
    ],
    'fleet.html': [
        ('<html lang="en">','<html lang="fr">'),
        ('<title>Fleet — FleetCommand</title>','<title>Flotte — FleetCommand</title>'),
        ('<div class="section-title" style="font-size:18px;">Fleet</div>','<div class="section-title" style="font-size:18px;">Flotte</div>'),
        ('<div class="section-subtitle">{FC.trucks.length} trucks · Live health overview</div>','<div class="section-subtitle">{FC.trucks.length} camions · Vue santé en direct</div>'),
        ('onclick="showToast(\'info\',\'Export\',\'Fleet report exported\')">📤 Export</button>','onclick="showToast(\'info\',\'Exporter\',\'Rapport de flotte exporté\')">📤 Exporter</button>'),
        ('onclick="showToast(\'success\',\'Updated\',\'Fleet health refreshed\')">⟳ Refresh</button>','onclick="showToast(\'success\',\'Actualisé\',\'Santé de flotte actualisée\')">⟳ Actualiser</button>'),
        ('<div class="section-title">Truck Health Signals</div>','<div class="section-title">Indicateurs de santé des camions</div>'),
        ('<div class="section-subtitle">Operational score by status</div>','<div class="section-subtitle">Score opérationnel par statut</div>'),
        ('<div class="payroll-name">Active</div>','<div class="payroll-name">Actifs</div>'),
        ('<div class="payroll-id">In service</div>','<div class="payroll-id">En service</div>'),
        ('<div class="payroll-name">Maintenance</div>','<div class="payroll-name">Maintenance</div>'),
        ('<div class="payroll-id">Requires attention</div>','<div class="payroll-id">Nécessite une attention</div>'),
        ('<div class="payroll-name">Idle</div>','<div class="payroll-name">Au repos</div>'),
        ('<div class="payroll-id">Waiting dispatch</div>','<div class="payroll-id">En attente de dispatch</div>'),
        ('<span style="font-size:13px;font-weight:600;color:var(--text-muted);" id="fleetCount">{FC.trucks.length} trucks</span>','<span style="font-size:13px;font-weight:600;color:var(--text-muted);" id="fleetCount">{FC.trucks.length} camions</span>'),
        ('placeholder="Search trucks…"','placeholder="Rechercher des camions…"'),
        ('<th>Truck</th><th>Status</th><th>Driver</th><th>Health</th><th>Mileage</th>','<th>Camion</th><th>Statut</th><th>Conducteur</th><th>Santé</th><th>Kilométrage</th>'),
        ('<th>Fuel</th><th>Next Service</th><th>Actions</th>','<th>Carburant</th><th>Prochaine révision</th><th>Actions</th>'),
        ('<button class="btn btn-ghost btn-xs" onclick="showToast(\'info\',\'Truck\',\'Opened ${t.id}\')">View</button>','<button class="btn btn-ghost btn-xs" onclick="showToast(\'info\',\'Camion\',\'Ouvert ${t.id}\')">Voir</button>'),
        ('<button class="btn btn-ghost btn-xs" onclick="showToast(\'success\',\'Task\',\'Inspection scheduled for ${t.id}\')">Inspect</button>','<button class="btn btn-ghost btn-xs" onclick="showToast(\'success\',\'Tâche\',\'Inspection programmée pour ${t.id}\')">Inspecter</button>'),
        ("initApp('Fleet <span class=\"topbar-subtitle\">— Trucks & Health</span>');","initApp('Flotte <span class=\"topbar-subtitle\">— Camions et santé</span>');"),
        ('Health avg: <span style="font-family:var(--font-mono);">','Moyenne santé : <span style="font-family:var(--font-mono);">'),
        ('mi','km'),
    ],
    'analytics.html': [
        ('<html lang="en">','<html lang="fr">'),
        ('<title>Analytics — FleetCommand</title>','<title>Analytique — FleetCommand</title>'),
        ('<div class="section-title" style="font-size:18px;">Analytics</div>','<div class="section-title" style="font-size:18px;">Analytique</div>'),
        ('<div class="section-subtitle">KPIs, insights & trends (mock)</div>','<div class="section-subtitle">Indicateurs, insights et tendances (maquette)</div>'),
        ('onclick="showToast(\'info\',\'Refresh\',\'Analytics recalculated\')">⟳ Refresh</button>','onclick="showToast(\'info\',\'Actualiser\',\'Analytique recalculée\')">⟳ Actualiser</button>'),
        ('onclick="showToast(\'success\',\'Report\',\'Analytics report generated\')">Generate Report</button>','onclick="showToast(\'success\',\'Rapport\',\'Rapport analytique généré\')">Générer le rapport</button>'),
        ('<div class="section-title">Revenue Trend</div>','<div class="section-title">Tendance des revenus</div>'),
        ('<div class="section-subtitle">Year-to-date (mock)</div>','<div class="section-subtitle">Année en cours (maquette)</div>'),
        ('<div class="section-title">Delivery Success</div>','<div class="section-title">Succès des livraisons</div>'),
        ('<div class="section-subtitle">On time vs delayed (mock)</div>','<div class="section-subtitle">Ponctuelles vs retardées (maquette)</div>'),
        ('<div class="section-title">Operations Metrics</div>','<div class="section-title">Indicateurs opérationnels</div>'),
        ('<div class="section-subtitle">Last 7 days</div>','<div class="section-subtitle">7 derniers jours</div>'),
        ('<div class="metric-label">Avg fuel spend</div>','<div class="metric-label">Dépenses carburant moy.</div>'),
        ('<div class="metric-label">On-time rate</div>','<div class="metric-label">Taux de ponctualité</div>'),
        ('<div class="metric-label">Delayed incidents</div>','<div class="metric-label">Incidents retardés</div>'),
        ('<div class="metric-label">Avg miles / trip</div>','<div class="metric-label">Km moy. / trajet</div>'),
        ('<div class="metric-label">Active drivers</div>','<div class="metric-label">Conducteurs actifs</div>'),
        ('<div class="section-title">Top Drivers</div>','<div class="section-title">Meilleurs conducteurs</div>'),
        ('<div class="section-subtitle">Based on earnings</div>','<div class="section-subtitle">Basé sur les revenus</div>'),
        ('<th>Driver</th><th>Status</th><th>Earnings</th><th>Rating</th>','<th>Conducteur</th><th>Statut</th><th>Revenus</th><th>Note</th>'),
        ("initApp('Analytics <span class=\"topbar-subtitle\">— Trends</span>');","initApp('Analytique <span class=\"topbar-subtitle\">— Tendances</span>');"),
        ("label:'Revenue'", "label:'Revenu'"),
    ],
    'payroll.html': [
        ('<html lang="en">','<html lang="fr">'),
        ('<title>Payroll — FleetCommand</title>','<title>Paie — FleetCommand</title>'),
        ('<div class="section-title" style="font-size:18px;">Payroll</div>','<div class="section-title" style="font-size:18px;">Paie</div>'),
        ('<div class="section-subtitle">Monthly overview · Mock totals</div>','<div class="section-subtitle">Vue mensuelle · Totaux factices</div>'),
        ('onclick="showToast(\'info\',\'Export\',\'Payroll exported\')">📄 Export</button>','onclick="showToast(\'info\',\'Exporter\',\'Paie exportée\')">📄 Exporter</button>'),
        ('onclick="showToast(\'success\',\'Run payroll\',\'Payroll run scheduled\')">▶ Run</button>','onclick="showToast(\'success\',\'Lancer\',\'Paie programmée\')">▶ Lancer</button>'),
        ('<div class="payroll-breakdown">Deliveries this month</div>','<div class="payroll-breakdown">Livraisons ce mois-ci</div>'),
        ('<span class="label">Trips</span>','<span class="label">Trajets</span>'),
        ('<span class="label">On Time</span>','<span class="label">Ponctualité</span>'),
        ('<button class="btn btn-ghost btn-xs" style="flex:1;" onclick="showToast(\'info\',\'Payout\',\'Payout details for ${d.id}\')">Details</button>','<button class="btn btn-ghost btn-xs" style="flex:1;" onclick="showToast(\'info\',\'Détails\',\'Détails de paiement pour ${d.id}\')">Détails</button>'),
        ('<button class="btn btn-ghost btn-xs" style="flex:1;" onclick="showToast(\'success\',\'Approved\',\'Payroll approved for ${d.id}\')">Approve</button>','<button class="btn btn-ghost btn-xs" style="flex:1;" onclick="showToast(\'success\',\'Approuvé\',\'Paie approuvée pour ${d.id}\')">Approuver</button>'),
        ("initApp('Payroll <span class=\"topbar-subtitle\">— Payout Overview</span>');","initApp('Paie <span class=\"topbar-subtitle\">— Vue des paiements</span>');"),
    ],
    'tracking.html': [
        ('<html lang="en">','<html lang="fr">'),
        ('<title>Live Tracking — FleetCommand</title>','<title>Suivi en direct — FleetCommand</title>'),
        ('<div class="section-title" style="font-size:18px;">Live Fleet Tracking</div>','<div class="section-title" style="font-size:18px;">Suivi en direct de la flotte</div>'),
        ('<div class="section-subtitle"><span class="live-dot"></span> {activeCount} vehicles active</div>','<div class="section-subtitle"><span class="live-dot"></span> {activeCount} véhicules actifs</div>'),
        ('onclick="showToast(\'info\',\'Legend\',\'Colors represent status\')">Legend</button>','onclick="showToast(\'info\',\'Légende\',\'Les couleurs représentent le statut\')">Légende</button>'),
        ('onclick="showToast(\'success\',\'Tracking\',\'Centered on all vehicles\')">Center All</button>','onclick="showToast(\'success\',\'Suivi\',\'Centré sur tous les véhicules\')">Centrer tout</button>'),
        ('<span style="color:var(--accent-cyan);">● Driving</span>','<span style="color:var(--accent-cyan);">● En route</span>'),
        ('<span style="color:var(--accent-green);">● Online</span>','<span style="color:var(--accent-green);">● En ligne</span>'),
        ('<span style="color:var(--accent-red);">● Maintenance/Delayed</span>','<span style="color:var(--accent-red);">● Maintenance/Retardé</span>'),
        ('<span style="color:var(--text-muted);">● Offline/Idle</span>','<span style="color:var(--text-muted);">● Inactif/Hors ligne</span>'),
        ('<div class="section-title">Fleet Summary</div>','<div class="section-title">Synthèse de la flotte</div>'),
        ('<div class="section-subtitle">Status breakdown</div>','<div class="section-subtitle">Répartition des statuts</div>'),
        ('<div class="section-title">Tracked Vehicles</div>','<div class="section-title">Véhicules suivis</div>'),
        ('<div class="section-subtitle">Click a pin for details</div>','<div class="section-subtitle">Cliquez sur une icône pour les détails</div>'),
        ('<thead><tr><th>Truck</th><th>Status</th><th>Driver</th><th>Health</th></tr></thead>','<thead><tr><th>Camion</th><th>Statut</th><th>Conducteur</th><th>État</th></tr></thead>'),
        ("initApp('Tracking <span class=\"topbar-subtitle\">— Live Map</span>');","initApp('Suivi <span class=\"topbar-subtitle\">— Carte en direct</span>');"),
        ("showToast('info','Truck ${t.id}','Health ${t.health}%')","showToast('info','Camion ${t.id}','Santé ${t.health}%')"),
    ],
}

for fname, reps in changes.items():
    path = root / fname
    if not path.exists():
        print('MISSING', fname)
        continue
    text = path.read_text(encoding='utf-8')
    orig = text
    for old, new in reps:
        text = text.replace(old, new)
    if text != orig:
        path.write_text(text, encoding='utf-8')
        print('UPDATED', fname)
    else:
        print('NO CHANGE', fname)
